<h1> Soal 1: Pemahaman Tentang Model Evaluasi</h1>

Jawab pertanyaan di bawah ini dengan bahasa masing-masing?

1. Apa perbedaan antara data latih, data validasi, dan data test?
2. Bagaimana cara kita menilai performa suatu model?
3. Apa itu Confusion Matrix? Jelaskan secara lengkap!
4. Apa itu Classification Report dari sklearn?

Jawab:
1. **Data latih** adalah data yang digunakan untuk melatih model. **Data validasi** adalah data yang digunakan untuk proses validasi model dan mencegah overlifting. **Data test** adalah data yang digunakan untuk menguji model, sebagai simulasi penggunaan model di dunia nyata.
2. Yaitu dengan menghitung score akurasi antara data validasi dan data test
3. Confusion Matrix adalah matriks yang digunakan untuk menguji performa algoritma model machine learning. Matriks berbentuk dua dimensi, berupa data sebenarnya dan tebakan dari model. Masing-masing dimensi dibagi menjadi nilai positif dan negatif. Untuk tebakan benar positif akan diberi nilai TP, tebakan salah positif FP, tebakan benar negatif TN, dan tebakan salah negatif FN.
4. Classification Report adalah suatu metode untuk menguji performa model dengan menampilkan nilai precision, recall, dan F1-score

---

<h1>Soal 2: Aplikasi Model Evaluasi</h1>

Kali ini kita akan menggunakan data untuk memprediksi kelangsungan hidup pasien yang telah mengalami operasi payudara. Dengan informasi yang dimiliki terkait pasien, kita akan membuat model untuk memprediksi apakah pasien akan bertahan hidup dalam waktu lebih dari 5 tahun atau tidak.

Lebih Lengkapnya kalian bisa membaca informasi tentang dataset di link berikut: https://raw.githubusercontent.com/jbrownlee/Datasets/master/haberman.names

Buat model Klasifikasi (Model/Algoritma Bebas) untuk memprediksi status pasien dengan ketentuan sebagai berikut:

1. Bagi kedua data ini menjadi data training dan data test dengan test_size=0.25.
3. Pelajar tentang metrics roc_auc_score kemudian buatlah model dan evaluasi dengan menggunakan teknik cross-validation dengan scoring 'roc_auc'. Baca https://scikit-learn.org/stable/modules/generated/sklearn.model_selection.cross_val_score.html untuk menggunakan metric roc_auc saat cross-validation.
3. Berapa score rata2 dari model dengan teknik cross-validation tersebut?
4. Prediksi data test dengan model yang telah kalian buat!
5. Bagaimana hasil confusion matrix dari hasil prediksi tersebut?
6. Bagaimana classification report dari hasil prediksi tersebut?
5. Seberapa baik model anda dalam memprediksi seorang pasien mempunyai status positive?
6. Seberapa baik model anda dalam memprediksi seorang pasien mempunyai status negatif?

In [ ]:
import pandas as pd

url = 'https://raw.githubusercontent.com/jbrownlee/Datasets/master/haberman.csv'
list_cols = ['Age', "Patient's Years", "N_positive_ax", "survival_status"]
df = pd.read_csv(url, names=list_cols)

In [ ]:
df.head()

Age  Patient's Years  N_positive_ax  survival_status
0   30               64              1                1
1   30               62              3                1
2   30               65              0                1
3   31               59              2                1
4   31               65              4                1

In [ ]:
df['survival_status'].value_counts()

1    225
2     81
Name: survival_status, dtype: int64

In [ ]:
# Code here
from sklearn.neighbors import KNeighborsClassifier
from sklearn import metrics
from sklearn.model_selection import train_test_split
x = df.drop('survival_status', axis=1)
y = df['survival_status']
x_train, x_test, y_train, y_test = train_test_split(x, y, test_size=0.25, random_state=10)

In [ ]:
model_knn=KNeighborsClassifier(n_neighbors=5)

In [ ]:
model_knn.fit(x_train, y_train)

KNeighborsClassifier(algorithm='auto', leaf_size=30, metric='minkowski',
                     metric_params=None, n_jobs=None, n_neighbors=5, p=2,
                     weights='uniform')

In [ ]:
y_pred=model_knn.predict(x_test)

In [ ]:
from sklearn.model_selection import cross_val_score
model_knn=KNeighborsClassifier(n_neighbors=5)
hasil = cross_val_score(model_knn, x, y,scoring='roc_auc', cv=5)

In [ ]:
hasil.mean()

0.6473039215686275

In [ ]:
from sklearn.metrics import confusion_matrix, classification_report
confusion_matrix(y_test, y_pred, labels=[2,1])

array([[ 4, 15],
       [ 8, 50]])

In [ ]:
TP=4
FN=15
FP=8
TN=50

In [ ]:
presisip=TP/(TP+FP)
recallp=TP/(TP+FN)
fsatup=2*presisip*recallp/(presisip+recallp)
presisin=TN/(TN+FN)
recalln=TN/(TN+FP)
fsatun=2*presisin*recalln/(presisin+recalln)

In [ ]:
presisin

0.7692307692307693

In [ ]:
print(classification_report(y_test, y_pred))

              precision    recall  f1-score   support

           1       0.77      0.86      0.81        58
           2       0.33      0.21      0.26        19

    accuracy                           0.70        77
   macro avg       0.55      0.54      0.54        77
weighted avg       0.66      0.70      0.68        77



In [ ]:
y_pred.shape

(77,)

---

<h1> Soal 3: Pemahaman Tentang Model Selection</h1>

Jelaskan dengan bahasa sendiri!

1. Apa itu Bias dan Variance?
2. Apa itu Overfitting dan Underfitting?
3. Apa yang bisa kita lakukan untuk mengatur kompleksitas dari model?
4. Bagaimana model yang baik?
5. Kapan kita menggunakan GridSearchcv dan kapan menggunakan RandomizedSearchCV?

Jawab:
1. Bias adalah perbedaan rata-rata antara hasil prediksi dari model Machine Learning dengan data nilai yang sebenarnya. Variance adalah variabel prediksi model untuk data tertentu di mana memberikan kita informasi persebaran data kita.
2. Overfitting adalah terjadinya beberapa penyimpangan dari data sebenarnya yang membuat model lebih sulit melihat hubungan data sebenarnya dengan data test. Underfitting adalah keadaan di mana model mengalami kegagalan mengenali kompleksitas nyata dalam data.
3. Melakukan tuning pada hyperparameter model
4. Model yang baik adalah model yang memiliki error bias dan error variance yang kecil
5. GridsearchCV digunakan ketika kita membuat parameter secara manual. RandomizedSearchCV digunakan ketika membuat hyperparameter secara acak.

---

<h1> Soal 4: Aplikasi Model Selection</h1>

1. Bagi kedua data berikut ini menjadi data training dan data test dengan test_size=0.25.
2. Gunakan algoritma KNN sebagai model classifier.
3. Gunakan fungsi GridSearchCV untuk hyperparameter tuning dan model selection.
4. jumlah fold bebas!, gunakan scoring 'roc_auc'
5. Definisikan kombinasi hyperparameter untuk model selection dengan GridSearchCV. kombinasi Hyperparameter bebas, baca lagi dokumentasi KNN di link berikut https://scikit-learn.org/stable/modules/generated/sklearn.neighbors.KNeighborsClassifier.html untuk memahami lagi jenis2 hyperparameter di algorithma KNN.
6. Latih model terhadap data training.
7. Apa hyperparameter terbaik untuk kombinasi hyperparameter kalian?
8. Berapa score validasi terbaik dari model tersebut?
9. Prediksi probabilitasi output dari model yang telah di buat terhadap data test. note : gunakan method .predict_proba() untuk menghasilkan output probabilitas
10. Perhatikan bahwa hasil prediksi ada 2, dimana masing2 adalah nilai probabilitas untuk setiap class label. Ambil nilai probabilitas pasien phositive meninggal dalam waktu kurang dari 5 tahun. note : gunakan bantuan attirubte .classes_ untuk mengetahui urutan label dari hasil prediksi probabilitas.
11. Berapa nilai score roc_auc untuk data test?
12. Apakah model anda termasuk baik, overtting, atau underfitting?
13. Ulangi tahap di atas namun kali ini menggunakan algoritma DecisionTreeClassifier dan kalian bisa menggunakan RandomizedSearchCV apabila process training lama. pelajari algoritma DecisionTreeClassifier di linkberikut: https://scikit-learn.org/stable/modules/generated/sklearn.tree.DecisionTreeClassifier.html?highlight=decisiontreeclassifier#sklearn.tree.DecisionTreeClassifier
14. Bandingkan scorenya dengan Algoritma KNN, mana yang lebih baik?

Note : Data Science adalah experiment, sangat di dimungkinkan memerlukan beberapa kali percobaan untuk mendapatkan hasil yang terbaik! Happy Coding :)

In [ ]:
import pandas as pd
import numpy as np

url = 'https://raw.githubusercontent.com/jbrownlee/Datasets/master/haberman.csv'
list_cols = ['Age', "Patient's Years", "N_positive_ax", "survival_status"]
df = pd.read_csv(url, names=list_cols)

In [ ]:
df.head()

Age  Patient's Years  N_positive_ax  survival_status
0   30               64              1                1
1   30               62              3                1
2   30               65              0                1
3   31               59              2                1
4   31               65              4                1

In [ ]:
# Code here
from sklearn.neighbors import KNeighborsClassifier
from sklearn.model_selection import train_test_split, GridSearchCV, RandomizedSearchCV, cross_val_score

x = df.drop('survival_status', axis=1)
y = df['survival_status']
x_train, x_test, y_train, y_test = train_test_split(x, y, test_size=0.25, random_state=10)
model_knn=KNeighborsClassifier()

In [ ]:
parapara = {'n_neighbors': np.arange(5, 50), 'weights':['distance', 'uniform']}
gscv = GridSearchCV(model_knn, param_grid=parapara, scoring='roc_auc', cv=5)
gscv.fit(x, y)

GridSearchCV(cv=5, error_score=nan,
             estimator=KNeighborsClassifier(algorithm='auto', leaf_size=30,
                                            metric='minkowski',
                                            metric_params=None, n_jobs=None,
                                            n_neighbors=5, p=2,
                                            weights='uniform'),
             iid='deprecated', n_jobs=None,
             param_grid={'n_neighbors': array([ 5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16, 17, 18, 19, 20, 21,
       22, 23, 24, 25, 26, 27, 28, 29, 30, 31, 32, 33, 34, 35, 36, 37, 38,
       39, 40, 41, 42, 43, 44, 45, 46, 47, 48, 49]),
                         'weights': ['distance', 'uniform']},
             pre_dispatch='2*n_jobs', refit=True, return_train_score=False,
             scoring='roc_auc', verbose=0)

In [ ]:
gscv.best_params_

{'n_neighbors': 40, 'weights': 'uniform'}

In [ ]:
gscv.best_score_

0.7151062091503269

In [ ]:
gscv.classes_

array([1, 2])

In [ ]:
gscv.predict_proba(x_test)

array([[0.8  , 0.2  ],
       [0.75 , 0.25 ],
       [0.875, 0.125],
       [0.725, 0.275],
       [0.4  , 0.6  ],
       [0.925, 0.075],
       [0.475, 0.525],
       [0.8  , 0.2  ],
       [0.85 , 0.15 ],
       [0.775, 0.225],
       [0.85 , 0.15 ],
       [0.875, 0.125],
       [0.775, 0.225],
       [0.475, 0.525],
       [0.8  , 0.2  ],
       [0.425, 0.575],
       [0.85 , 0.15 ],
       [0.875, 0.125],
       [0.525, 0.475],
       [0.8  , 0.2  ],
       [0.8  , 0.2  ],
       [0.875, 0.125],
       [0.65 , 0.35 ],
       [0.75 , 0.25 ],
       [0.9  , 0.1  ],
       [0.875, 0.125],
       [0.875, 0.125],
       [0.775, 0.225],
       [0.85 , 0.15 ],
       [0.75 , 0.25 ],
       [0.775, 0.225],
       [0.8  , 0.2  ],
       [0.775, 0.225],
       [0.85 , 0.15 ],
       [0.775, 0.225],
       [0.825, 0.175],
       [0.9  , 0.1  ],
       [0.775, 0.225],
       [0.7  , 0.3  ],
       [0.8  , 0.2  ],
       [0.875, 0.125],
       [0.375, 0.625],
       [0.475, 0.525],
       [0.8

In [ ]:
from sklearn.tree import DecisionTreeClassifier
pohon = DecisionTreeClassifier()

In [ ]:
param={'criterion': ['gini', 'entropy'], 'splitter':['best', 'random'], 'max_depth': np.arange(2, 20)}
rscv=RandomizedSearchCV(pohon, param, scoring='roc_auc', cv=5)
rscv.fit(x,y)

RandomizedSearchCV(cv=5, error_score=nan,
                   estimator=DecisionTreeClassifier(ccp_alpha=0.0,
                                                    class_weight=None,
                                                    criterion='gini',
                                                    max_depth=None,
                                                    max_features=None,
                                                    max_leaf_nodes=None,
                                                    min_impurity_decrease=0.0,
                                                    min_impurity_split=None,
                                                    min_samples_leaf=1,
                                                    min_samples_split=2,
                                                    min_weight_fraction_leaf=0.0,
                                                    presort='deprecated',
                                                    random_state=None,
          

In [ ]:
rscv.best_score_

0.6018545751633988